"""Plan history ORM model."""

from datetime import datetime

from sqlalchemy import DateTime, Integer, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.database.connection import Base


class Plan(Base):
    """Stored project plan generated by the AI."""

    __tablename__ = "plans"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    project_idea: Mapped[str] = mapped_column(Text, nullable=False)
    industry: Mapped[str] = mapped_column(Text, nullable=False, default="Other")
    budget: Mapped[str] = mapped_column(Text, nullable=False, default="Medium")
    project_type: Mapped[str] = mapped_column(Text, nullable=False, default="MVP")
    experience_level: Mapped[str] = mapped_column(Text, nullable=False, default="Intermediate")
    generated_plan: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
